version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      - DB_URL=postgresql://user:password@timescaledb/ohlcv
    depends_on:
      - timescaledb
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ohlcv
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
